version: '3.8'

services:
  wallet-api:
    depends_on:
      - postgres
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=wallet_db

    networks:
      - wallet-net

  postgres:
    image: postgres:13
    container_name: wallet-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - wallet_db_data:/var/lib/postgresql/data
    networks:
      - wallet-net

volumes:
  wallet_db_data:

networks:
  wallet-net:
    driver: bridge
